#!/bin/sh

cd /app

mvn -am spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" & \

while true; do
  inotifywait -e modify,create,delete,move -r ./src/main/java && mvn compile
done